apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      # labels are matched by selector
      # so deployment knows which pods belongs to it
      app: nginx
  template:
    # applies to pod
    metadata:
      labels: 
        app: nginx
    spec:
      # blueprint for pods
      containers:
      - name: nginx
        image: nginx:1.16
        ports:
        - containerPort: 8080
